### ISSUE TITLE
how to apk generate in windows 

### ISSUE THREAD

**Issue by Coding-Meet** [its-me-debk007/gradle-version-catalog-migrator#2]
I try this assembleDebug not work

![image](https://github.com/its-me-debk007/gradle-version-catalog-migrator/assets/131579912/606a956b-a1a1-4a23-9912-ca42c2418695)

**Comment by its-me-debk007** [comment]
Hi @Coding-Meet,

Sorry for the inconvenience, I had used workflow from my previous project. Didn't noticed it was android specific.

Now I've corrected the workflow. Also artifact for both Linux and Windows is available!
